sudo: required
dist: trusty
language: python
python:
- '3.5'
- '3.6'
env:
  matrix:
  - DB=postgres
addons:
  postgresql: '9.5'
services:
- postgresql
- rabbitmq
install: source .travis/install.sh
script: skip
stages:
- name: test
- name: deploy
  if: tag =~ ^3.0.0b*
jobs:
  include:
  - stage: test
    before_script: source .travis/before_script.sh
    script: source .travis/script.sh
    after_failure:
    - sh -c "cat ~/django_runserver.log"
    - sh -c "cat ~/resource_manager.log"
    - sh -c "cat ~/reserved_workers-1.log"
  - stage: deploy
    script: skip
    deploy:
      provider: pypi
      distributions: sdist bdist_wheel
      user: pulp
      password:
        secure: g22+zK7xVzjuJ8b76p9huAfujOMpz/LAGXniqfp7cNZ2tleq5uOIHV7bTHrP7dsLomDBhr7RMdk/SbPO+Liuuwto9/rMSKTjzCHK2jhLYKIxbG+8xadD7J86uZtxwzHJtbHoSTSI6efGZg7arfEAu15k2OPLwDHFjXtV8GoXkY0=
