# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 01:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pulp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PythonImporter',
            fields=[
                ('importer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pulp_app.Importer')),
                ('project_names', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('pulp_app.importer',),
        ),
        migrations.CreateModel(
            name='PythonPackageContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pulp_app.Content')),
                ('filename', models.TextField(db_index=True, unique=True)),
                ('packagetype', models.TextField()),
                ('name', models.TextField()),
                ('version', models.TextField()),
                ('metadata_version', models.TextField()),
                ('summary', models.TextField(null=True)),
                ('description', models.TextField(max_length=4096, null=True)),
                ('keywords', models.TextField(null=True)),
                ('home_page', models.TextField(null=True)),
                ('download_url', models.TextField(null=True)),
                ('author', models.TextField(null=True)),
                ('author_email', models.TextField(null=True)),
                ('maintainer', models.TextField(null=True)),
                ('maintainer_email', models.TextField(null=True)),
                ('license', models.TextField(null=True)),
                ('requires_python', models.TextField(null=True)),
                ('project_url', models.TextField(null=True)),
                ('platform', models.TextField(null=True)),
                ('supported_platform', models.TextField(null=True)),
                ('requires_dist', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('provides_dist', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('obsoletes_dist', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('requires_external', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('pulp_app.content',),
        ),
        migrations.CreateModel(
            name='PythonPublisher',
            fields=[
                ('publisher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pulp_app.Publisher')),
            ],
            options={
                'abstract': False,
            },
            bases=('pulp_app.publisher',),
        ),
        migrations.AddField(
            model_name='classifier',
            name='python_package_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifiers', related_query_name='classifier', to='pulp_python.PythonPackageContent'),
        ),
    ]
