# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulp_python', '0002_auto_20171211_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonpackagecontent',
            name='description',
            field=models.TextField(max_length=10240, null=True),
        ),
    ]
