# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulp_python', '0003_auto_20171211_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonpackagecontent',
            name='description',
            field=models.TextField(max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='pythonpackagecontent',
            name='summary',
            field=models.TextField(max_length=8192, null=True),
        ),
    ]
